version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: relsheet-backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=relsheet
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    stdin_open: true   # 👈 TEMPORARY for running `startproject` and `startapp`
    tty: true

  frontend:
    build:
      context: ./frontend
    container_name: relsheet-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm run dev
    stdin_open: true   # 👈 TEMPORARY for running the Next.js scaffolder
    tty: true
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: relsheet-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: relsheet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
